name: myfoody
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_riverpod: ^2.1.1
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  freezed: ^2.1.1
  go_router: ^4.5.1
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_serializable: ^6.5.4
  pretty_dio_logger: ^1.1.1
  # riverpod_annotation: ^1.0.6
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen: ^5.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true # Enables FlutterGenImage

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
